openapi: 3.1.0
info:
  title: Open Podcast API
  description: |
    This is the OpenAPI specification for the Open Podcast API. For more information, check the specs at <https://openpodcastapi.org/>.
  version: 0.1.0
tags:
  - name: Authentication
    description: All actions relating to authentication
  - name: Synchronization
    description: The core synchronization endpoint
  - name: Subscriptions
    description: Endpoints relating to podcast subscriptions
paths:
  /auth/login:
    post:
      tags:
        - Authentication
      summary: Log in to the server
      description: |
        Logs a user in to the server and provides access credentials for the requesting client
      operationId: login
      requestBody:
        $ref: '#/components/requestBodies/Login'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          $ref: '#/components/responses/NotAuthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh an access token
      description: |
        Generates a new access token using an existing valid refresh token
      operationId: refreshToken
      requestBody:
        $ref: '#/components/requestBodies/RefreshToken'
      responses:
        '200':
          description: Successful token refresh
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenResponse'
        '401':
          description: Refresh token is expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                description: The supplied refresh token has expired. Please reauthenticate
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/sync:
    get:
      tags:
        - Synchronization
      summary: Sync from the server
      description: Fetch actions taken since the specified last sync time
      security:
        - bearerAuth: []
      operationId: fetchSync
      parameters:
        - name: since
          in: query
          description: The most recent update timestamp to fetch data from
          schema:
            type: string
            format: date-time
        - name: limit
          description: The number of results to include per page
          in: query
          schema:
            type: number
            format: int64
            default: 50
        - name: include
          in: query
          description: |
            The entities to include in the response. Defaults to `all`
          schema:
            type: string
            enum:
              - all
              - subscriptions
            default: all
        - name: include_own
          in: query
          description: |
            Whether to include updates made by the requesting device. Defaults to `false`
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Sync requested successfully
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required:
                      - results
                    properties:
                      results:

        '401':
          description: Access token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                description: The supplied access token is invalid
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      tags:
        - Synchronization
      operationId: postSync
      description: |
        Post up to 30 actions per batch
      security:
        - bearerAuth: []
      parameters:
        - name: Client-ID
          in: header
          description: A unique identifier generated by the client for excluding results
          schema:
            type: string
            format: uuid
      requestBody:
        summary: Sync request
        description: The array of actions sent to the client
        $ref: '#/components/requestBodies/SyncAction'
      responses:
        '200':
          description: Actions handled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SyncActionResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Bad request
                description: The request payload is invalid. Check the number of entries.
        '401':
          description: Access token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                description: The supplied access token is invalid
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/subscriptions:
    get:
      tags:
        - Subscriptions
      operationId: getSubscriptions
      security:
        - bearerAuth: []
      parameters:
        - name: include_unsubscribed
          description: Whether to include unsubscribed feeds in the response
          in: query
          schema:
            type: boolean
            default: false
        - name: since
          description: The cursor position to start at
          in: query
          schema:
            type: string
        - name: limit
          description: The number of results to include per page
          in: query
          schema:
            type: number
            format: int64
            default: 50
      responses: 
        '200':
          description: Subscriptions found
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    required:
                      - results
                    properties:
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/PersistedSubscription'
                  - $ref: '#/components/schemas/Pagination'
                examples:
                  - results:
                    - sync_id: 4648b4d7-90bf-497c-a5e7-8383d1083d76
                      guid: 677ea490-690e-51cb-8b43-755df6c55270
                      feed_url: https://example.com/feed1
                      subscribed_at: 2026-07-11T15:30:00.1Z
                    - sync_id: aa840671-fc3b-430b-b8f2-92e6e9c7832b
                      guid: a388867e-ce91-54d3-a116-114b07bb84e9
                      feed_url: https://example.com/feed2
                      subscribed_at: 2026-03-15T12:06:04.1Z
                      unsubscribed_at: 2026-07-12T12:10:00.1Z
                    has_next: true
                    next_cursor: /api/v1/subscriptions?since=3
        '401':
          description: Access token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                description: The supplied access token is invalid
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/subscriptions/{sync_id}:
    get:
      tags:
        - Subscriptionsh
      operationId: getSubscription
      security:
        - bearerAuth: []
      parameters:
        - name: sync_id
          in: path
          description: The unique sync ID of the subscription
          schema:
            type: string
            format: uuid
          required: true
      responses:
        '200':
          description: Subscription found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersistedSubscription'
        '401':
          description: Access token is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Unauthorized
                description: The supplied access token is invalid
        '404':
          description: Subscription not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: Not found
                description: The requested subscription was not found
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  requestBodies:
    Login:
      description: A login request payload
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginRequest'
    RefreshToken:
      description: A refresh token request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RefreshTokenRequest'
    SyncAction:
      description: A sync action
      content:
        application/json:
          schema:
            type: object
            required:
              - requests
            properties:
              requests:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/SubscriptionAction'
                  discrimintator:
                    propertyName: type
                    mapping:
                      subscription: '#/components/schemas/SubscriptionAction'
  responses:
    NotAuthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: Unauthorized
            description: The username or password is incorrect
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: Internal server error
            description: The server encountered an error while processing the request
  schemas:
    Error:
      description: Generic error object
      type: object
      required:
        - error
        - description
      properties:
        error:
          type: string
          description: The error message
        description:
          type: string
          description: The error description
    Pagination:
      description: Pagination properties for paginated results
      type: object
      required:
        - has_next
      properties:
        has_next:
          type: boolean
          description: Whether there is a next page of results
        next_cursor:
          type: string
          format: url
          description: The URL of the next page of results, if available
        prev_cursor:
          type: string
          format: url
          description: The URL of the previous page of results, if available
    LoginResponse:
      description: A response object containing an access token and refresh token
      allOf:
        - $ref: '#/components/schemas/AccessTokenResponse'
        - $ref: '#/components/schemas/RefreshTokenResponse'
      examples:
        - access_token: G6IWgOSDfXylCr8donVs5wlnfaBvv6EszuKcppz9XXbC9AqiT5jp161nN05jghcQ2OQ/JMRvSaUQxf6L9fWVYA==
          expires_in: 3600
          refresh_token: vRT0XmbTHs3KzrPZJD8F92AWnOrPk9o781mQkP63iyZZ8MNzfpd5x5xVRojFrjXmM72vYe3I9v/PR16dzHxgkg==
          refresh_expires: 2026-07-11T15:30:00Z
          refresh_endpoint: /auth/refresh
    LoginRequest:
      type: object
      description: A login request payload
      required:
        - username
        - password
      properties:
        username:
          type: string
          description: The username of the requesting user
        password:
          type: string
          description: The password of the requesting user
      examples:
        - username: example-user
          password: example-password
    AccessTokenResponse:
      type: object
      description: A response object containing a refreshed access token
      required:
        - access_token
        - expires_in
      properties:
        access_token:
          type: string
          description: The access token generated by the server
        expires_in:
          type: number
          description: The lifetime of the access token, in seconds
      examples: 
        - access_token: G6IWgOSDfXylCr8donVs5wlnfaBvv6EszuKcppz9XXbC9AqiT5jp161nN05jghcQ2OQ/JMRvSaUQxf6L9fWVYA==
          expires_in: 3600
    RefreshTokenRequest:
      type: object
      description: A refresh token request
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
          description: The refresh token held by the client
      examples:
        - refresh_token: vRT0XmbTHs3KzrPZJD8F92AWnOrPk9o781mQkP63iyZZ8MNzfpd5x5xVRojFrjXmM72vYe3I9v/PR16dzHxgkg==
    RefreshTokenResponse:
      type: object
      description: A response object containing a refresh token
      required:
        - refresh_token
        - refresh_expires
        - refresh_endpoint
      properties:
        refresh_token:
          type: string
          description: The refresh token generated by the server
        refresh_expires:
          type: string
          format: date-time
          description: The UTC timestamp at which the refresh token expires
        refresh_endpoint:
          type: string
          format: url
          description: The endpoint used to refresh the access token
      examples:
        - refresh_token: vRT0XmbTHs3KzrPZJD8F92AWnOrPk9o781mQkP63iyZZ8MNzfpd5x5xVRojFrjXmM72vYe3I9v/PR16dzHxgkg==
          refresh_expires: 2026-07-11T15:30:00Z
          refresh_endpoint: /auth/refresh
    EntityType:
      type: string
      description: The type of entity targeted by an action
      enum:
        - subscription
    ActionObject:
      type: object
      description: An object containing action information
      required:
        - type
        - action
        - action_id
        - occurred_at
        - data
      properties:
        type:
          $ref: '#/components/schemas/EntityType'
        action:
          type: string
          description: The action being taken on the target
        action_id:
          type: string
          format: uuid
          description: A client-generated UUID identifier for the action
        occurred_at:
          type: string
          format: date-time
          description: The UTC timestamp of when the action was undertaken on the client
        data:
          anyOf:
            - $ref: '#/components/schemas/Subscription'
    Subscription:
      type: object
      required:
        - guid
        - feed_url
        - subscribed_at
      properties:
        sync_id:
          type: string
          format: uuid
          description: The server-generated synchronization ID for the subscription
        guid:
          type: string
          description: |
            The `guid` field as found in the podcast's RSS feed
        feed_url:
          type: string
          format: url
          description: The canonical address of the podcast RSS feed
        subscribed_at:
          type: string
          format: date-time
          description: The UTC timestamp at which the user subscribed to the feed
        unsubscribed_at:
          type: string
          format: date-time
          description: The UTC timestamp at which the user unsubscribed from the feed
      examples: 
        - sync_id: 4648b4d7-90bf-497c-a5e7-8383d1083d76
          guid: 677ea490-690e-51cb-8b43-755df6c55270
          feed_url: https://example.com/feed1
          subscribed_at: 2026-07-11T15:30:00.1Z
        - sync_id: aa840671-fc3b-430b-b8f2-92e6e9c7832b
          guid: a388867e-ce91-54d3-a116-114b07bb84e9
          feed_url: https://example.com/feed2
          subscribed_at: 2026-03-15T12:06:04.1Z
          unsubscribed_at: 2026-07-12T12:10:00.1Z
    PersistedSubscription:
      type: object
      required:
        - sync_id
        - guid
        - feed_url
        - subscribed_at
      $ref: '#/components/schemas/Subscription'
    ActionId:
      type: string
      format: uuid
      description: The client-generated UUIDv4 identifier for the action
    SyncAction:
      type: object
      required:
        - action_id
        - occurred_at
        - type
        - action
        - data
      properties:
        action_id:
          $ref: '#/components/schemas/ActionId'
        occurred_at:
          type: string
          format: date-time
          description: The UTC timestamp at which the action occurred on the client
        type:
          type: string
        action:
          type: string
        data:
          type: object

    SubscriptionActions:
      type: string
      enum:
        - subscribe
        - unsubscribe
        - update
    SubscriptionAction:
      allOf:
        - $ref: '#/components/schemas/SyncAction'
        - type: object
          properties:
            action:
              $ref: '#/components/schemas/SubscriptionActions'
            type:
              type: string
              description: The target entity type
              enum:
                - subscription
            data:
              $ref: '#/components/schemas/Subscription'
    ActionResult:
      type: object
      required:
        - type
        - action
        - action_id
        - status
        - data
      properties:
        type:
          type: string
          description: The target entity type
          enum:
            - subscription
        action:
          allOf:
            - $ref: '#/components/schemas/SubscriptionActions'
        action_id:
          $ref: '#/components/schemas/ActionId'
        status:
          type: string
          description: The status of the action
          enum:
            - applied
            - ignored
            - rejected
        data:
          type: object
          description: The canonical state of the target entity
    SubscriptionActionResult:
      allOf:
        - $ref: '#/components/schemas/ActionResult'
        - type: object
          properties:
            action: 
              $ref: '#/components/schemas/SubscriptionActions'
            type:
              type: string
              description: The target entity type
              enum:
                - subscription
            data:
              $ref: '#/components/schemas/PersistedSubscription'
    SyncActionResponse:
      type: object
      required:
        - results
      properties:
        results:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/SubscriptionActionResult'
            discrimintator:
              propertyName: type
              mapping:
                subscription: '#/components/schemas/SubscriptionActionResult'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT